# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TdH8_AUoJJdtRv6BWw5Lz89TZGvyUp8-
"""

import numpy as np
import pandas as pd
df1 = pd.read_csv("raw_data1.csv")
df2 = pd.read_csv("district.csv")
df2_district_list = df2["District"].tolist()
df1_district_list = df1["Detected District"].tolist()
df2_sum = df2["sum"].tolist()
df1_sum = df1["Num Cases"].tolist()
for i in range(len(df1)):
  if (df1_district_list[i] in df2_district_list):
    k=(df2_district_list.index(df1_district_list[i]))
    df2_sum[k] = df2_sum[k] + df1_sum[df1_district_list.index(df1_district_list[i])]
print(df2_sum)
df2_sum.to_csv("case-time.csv")