# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TdH8_AUoJJdtRv6BWw5Lz89TZGvyUp8-
"""

#weekly statewise
import numpy as np
import pandas as pd
df1 = pd.read_csv("cowin_vaccine_data_districtwise.csv")
groupby_sum1 = df1.groupby(['State']).sum() 


from datetime import datetime
df1['Updated On'] = df1['Updated On'].astype('datetime64[ns]')

weekly_data = df1.groupby(["State"]).resample('W-Wed', label='right', closed = 'right', on='Updated On').sum().reset_index().sort_values(by='Updated On')
w = (weekly_data[["Updated On","State","First Dose Administered","Second Dose Administered"]])
w.to_csv("vaccinated-count-time_district.csv")