# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TdH8_AUoJJdtRv6BWw5Lz89TZGvyUp8-
"""

#state wise overall
import numpy as np
import pandas as pd
df1 = pd.read_csv("cowin_vaccine_data_statewise (1).csv")
groupby_sum1 = df1.groupby(['State']).sum() 
print(groupby_sum1[['First Dose Administered','Second Dose Administered']])
groupby_sum1[['First Dose Administered','Second Dose Administered']].to_csv("vaccinated_count_time_state.csv")